add new macro ADVANCE_CHAR_INCREMENT to avoid GCC-4.9 build error
Current version of json-c cannot be build with FSF GCC-4.9.0 because
of the following build error:

json_tokener.c:213:36: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
    ( ++(str), ((tok)->char_offset)++, c)
                                     ^
json_tokener.c:479:14: note: in expansion of macro 'ADVANCE_CHAR'
              ADVANCE_CHAR(str, tok);
              ^
json_tokener.c:213:36: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
   ( ++(str), ((tok)->char_offset)++, c)
                                    ^
json_tokener.c:480:14: note: in expansion of macro 'ADVANCE_CHAR'
              ADVANCE_CHAR(str, tok);

It is caused with the fact the GCC-4.9.0 "now warns about unused
right-hand side of a comma expression that contains no side effects",
according to https://gcc.gnu.org/gcc-4.9/porting_to.html

That's why to provide future opportunity to build json-c with newer
version of compiler, there had been added a special macro
ADVANCE_CHAR_INCREMENT that does not use comma expression and only
performs 2 incrementations.

The patch has been tested both for old old (gcc-4.8) and
new (gcc-4.9) versions of compiler for architectures: i586, armv7l,
aarch64, x86_64. See project devel:arm_toolchain:Mobile:test
at build.tizen.org for build results.

Change-Id: Ie57ddd95c3c50777460b4a7e8c7f8e1a709beeda
Signed-off-by: Ilya Palachev <i.palachev@samsung.com>